language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y lua5.1 luarocks libfreetype6-dev libfontconfig1-dev libpng-dev liblua5.1-lpeg2 liblua5.1-expat0 fonts-sil-gentium
 - wget http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-0.9.26.tar.bz2
 - tar xf harfbuzz-0.9.26.tar.bz2
 - cd harfbuzz-0.9.26
 - ./configure && make && sudo make install
 - sudo ldconfig
 - cd ../
 - sudo luarocks install busted
script:
 - sh bootstrap.sh && ./configure && make
 - busted -m './lua-libraries/?.lua;./lua-libraries/?/init.lua' tests
 - perl tests/attack.pl
