subdir_files = \
  core/colorparser.lua \
  core/inputs-xml.lua \
  core/libtexpdf-output.lua \
  core/pango-shaper.lua \
  core/frame.lua \
  core/typesetter.lua \
  core/languages.lua \
  core/measurements.lua \
  core/settings.lua \
  core/baseclass.lua \
  core/sile.lua \
  core/parserbits.lua \
  core/podofo-output.lua \
  core/harfbuzz-shaper.lua \
  core/nodefactory.lua \
  core/papersizes.lua \
  core/font.lua \
  core/cairo-output.lua \
  core/frameparser.lua \
  core/length.lua \
  core/pagebuilder.lua \
  core/break.lua \
  core/inputs-common.lua \
  core/inputs-texlike.lua \
  core/hyphenator-liang.lua \
  core/utilities.lua \
  classes/diglot.lua \
  classes/book.lua \
  classes/docbook.lua \
  classes/docbook.sil \
  classes/plain.lua \
  languages/cs.lua \
  languages/lt.lua \
  languages/pa.lua \
  languages/id.lua \
  languages/rm.lua \
  languages/el.lua \
  languages/is.lua \
  languages/sk.lua \
  languages/as.lua \
  languages/el-polyton.lua \
  languages/mr.lua \
  languages/bg.lua \
  languages/ta.lua \
  languages/lv.lua \
  languages/hu.lua \
  languages/hr.lua \
  languages/et.lua \
  languages/da.lua \
  languages/es.lua \
  languages/sv.lua \
  languages/bn.lua \
  languages/cy.lua \
  languages/tk.lua \
  languages/eu.lua \
  languages/ml.lua \
  languages/ca.lua \
  languages/nl.lua \
  languages/it.lua \
  languages/hi.lua \
  languages/sl.lua \
  languages/uk.lua \
  languages/sa.lua \
  languages/fr.lua \
  languages/de.lua \
  languages/ja.lua \
  languages/xx.lua \
  languages/no.lua \
  languages/bo.lua \
  languages/or.lua \
  languages/th.lua \
  languages/pt.lua \
  languages/gu.lua \
  languages/ro.lua \
  languages/ga.lua \
  languages/af.lua \
  languages/el-monoton.lua \
  languages/ru.lua \
  languages/tr.lua \
  languages/pl.lua \
  languages/ka.lua \
  languages/sr.lua \
  languages/en.lua \
  languages/kn.lua \
  languages/fi.lua \
  languages/la.lua \
  packages/tableofcontents.lua \
  packages/frametricks.lua \
  packages/folio.lua \
  packages/twoside.lua \
  packages/image.lua \
  packages/masters.lua \
  packages/color.lua \
  packages/footnotes.lua \
  packages/infonode.lua \
  packages/verbatim.lua \
  packages/lorem.lua \
  packages/insertions.lua \
  packages/indexer.lua \
  packages/simpletable.lua \
  packages/balanced-frames.lua \
  packages/rotate.lua \
  packages/rules.lua \
  packages/pagebuilder-bestfit.lua \
  packages/raiselower.lua \
  packages/counters.lua \
  packages/xmltricks.lua \
  packages/bidi.lua \
  packages/grid.lua \
  lua-libraries/imagesize.lua \
  lua-libraries/std/functional.lua \
  lua-libraries/std/list.lua \
  lua-libraries/std/string.lua \
  lua-libraries/std/modules.lua \
  lua-libraries/std/io.lua \
  lua-libraries/std/debug_init/init.lua \
  lua-libraries/std/object.lua \
  lua-libraries/std/container.lua \
  lua-libraries/std/math.lua \
  lua-libraries/std/strbuf.lua \
  lua-libraries/std/tree.lua \
  lua-libraries/std/debug.lua \
  lua-libraries/std/optparse.lua \
  lua-libraries/std/set.lua \
  lua-libraries/std/base.lua \
  lua-libraries/std/package.lua \
  lua-libraries/std/strict.lua \
  lua-libraries/std/table.lua \
  lua-libraries/std.lua \
  lua-libraries/epnf.lua \
  lua-libraries/unicode-bidi-algorithm.lua \
  lua-libraries/lomwithpos.lua \
  lua-libraries/imagesize/format/xpm.lua \
  lua-libraries/imagesize/format/pcd.lua \
  lua-libraries/imagesize/format/xbm.lua \
  lua-libraries/imagesize/format/tiff.lua \
  lua-libraries/imagesize/format/psd.lua \
  lua-libraries/imagesize/format/bmp.lua \
  lua-libraries/imagesize/format/mng.lua \
  lua-libraries/imagesize/format/png.lua \
  lua-libraries/imagesize/format/swf.lua \
  lua-libraries/imagesize/format/xcf.lua \
  lua-libraries/imagesize/format/jpeg.lua \
  lua-libraries/imagesize/format/gif.lua \
  lua-libraries/imagesize/format/pnm.lua \
  lua-libraries/imagesize/util.lua \
  lua-libraries/bit32-compat.lua \
  lua-libraries/char-def.lua \
  lua-libraries/repl/console.lua \
  lua-libraries/repl/sync.lua \
  lua-libraries/repl/init.lua \
  lua-libraries/repl/utils.lua \
  lua-libraries/repl/plugins/completion.lua \
  lua-libraries/repl/plugins/semicolon_suppress_output.lua \
  lua-libraries/repl/plugins/history.lua \
  lua-libraries/repl/plugins/rcfile.lua \
  lua-libraries/repl/plugins/autoreturn.lua \
  lua-libraries/repl/plugins/keep_last_eval.lua \
  lua-libraries/repl/plugins/linenoise.lua \
  lua-libraries/repl/plugins/example.lua \
  lua-libraries/repl/plugins/pretty_print.lua \
  lua-libraries/cassowary.lua
